#!/bin/bash

# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source bash-colors

colors=(red green yellow blue magenta cyan gray)
styles=(bold italics underline reverse strike)

for color in ${colors[*]}; do
    printf "%s%-7s%s " "\${$color}" "$color" "\${reset}"
    printf "%s%-8s%s " "\${d$color}" "d$color" "\${reset}"
    for style in ${styles[*]}; do
        printf "%s%-17s%s " "\${$color}\${$style}" "$style $color" "\${reset}"
    done
    echo
done
